spring:
  datasource:
    url: @geocode-ws.db.url@
    username: @geocode-ws.db.username@
    password: @geocode-ws.db.password@
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maximumPoolSize: 12
      minimumIdle: 2
  liquibase:
    enabled: false
  shapefiles:
    root: /mnt/auto/scratch/mblissett/layers/

  jmx:
    enabled: true
