spring:
  datasource:
    url: @geocode-ws.db.url@
    username: @geocode-ws.db.username@
    password: @geocode-ws.db.password@
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maximumPoolSize: 12
      minimumIdle: 2
  liquibase:
    enabled: false
  shapefiles:
    root: @geocode-ws.shapefiles.path@
    enabled: PoliticalLayer, ContinentLayer, IhoLayer, GadmLayer, WdpaLayer, WgsrpdLayer
  defaultLayers: Political, Continent, Centroids, IHO, GADM, WDPA, WGSRPD

  jmx:
    enabled: true
